In [1]:
%pip install numpy

   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ------ --------------------------------- 2.1/12.3 MB 11.6 MB/s eta 0:00:01
   --------------- ------------------------ 4.7/12.3 MB 11.7 MB/s eta 0:00:01
   ---------------------- ----------------- 7.1/12.3 MB 11.5 MB/s eta 0:00:01
   ------------------------------ --------- 9.4/12.3 MB 11.7 MB/s eta 0:00:01
   ---------------------------------------  12.1/12.3 MB 11.7 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 11.0 MB/s  0:00:01
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
ones = np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [4]:
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
eye = np.eye((4))
print(eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [6]:
random_arr = np.random.rand(3,2)
print(random_arr)

[[0.3204763  0.58231185]
 [0.17778273 0.34984806]
 [0.57313358 0.43740571]]


In [7]:
np.arange(0,10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(2,25,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23])

In [9]:
arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])

print(arr[2,2]) # by indexing
print(arr[2]) # row
print(arr[:,1]) # column

90
[70 80 90]
[20 50 80]


In [10]:
a = np.array([98,33,12])
b = np.array([34,63,84])

print(a)
print("________________________________")
print(b)
print("________________________________")

print("Addition :", a + b )
print("________________________________")
print("Subtraction :", a - b )
print("________________________________")
print("Multiplication :", a * b )
print("________________________________")
print("Division :", a / b )
print("________________________________")


[98 33 12]
________________________________
[34 63 84]
________________________________
Addition : [132  96  96]
________________________________
Subtraction : [ 64 -30 -72]
________________________________
Multiplication : [3332 2079 1008]
________________________________
Division : [2.88235294 0.52380952 0.14285714]
________________________________


In [11]:
print("Dot Product", np.dot(a,b))
print("________________________________")
print("Cross Product", np.cross(a,b))
print("________________________________")

Dot Product 6419
________________________________
Cross Product [ 2016 -7824  5052]
________________________________


In [13]:
arr_1 = np.arange(1,10)

reshaped = arr_1.reshape(3,3)

print(arr_1)
print("-----")
print(reshaped)
print("-----")


[1 2 3 4 5 6 7 8 9]
-----
[[1 2 3]
 [4 5 6]
 [7 8 9]]
-----


In [14]:
flattened = reshaped.flatten()

print(flattened)

[1 2 3 4 5 6 7 8 9]
